# :auto_namespace: true
:bin_defaults:
- boson_method_missing
:console_defaults:
- boson_method_missing
- completion
- alias
- method_lister
- core_gem
- misc
- boson
- irb_features
- local_gem
- duration
- hirb
- every
- rails/logger
- rails/personal
- irb_core
:libraries:
  method_lister:
    :object_methods: false
    :commands:
    - mls
    - mwhich
    - mgrep
  basic_shell:
    :class_commands:
      cd : Dir.chdir
      pwd: Dir.pwd
  alias:
    :object_methods: false
    :no_alias_creation: true
    :class_commands:
      create_aliases: Alias::Console.create_aliases
      save_aliases: Alias::Console.save_aliases
  completion:
    :class_commands:
      spy: Bond.spy
  history:
    :dependencies:
      - console
      - boson
  highline:
    :commands:
    - agree
    - ask
    - choose
    - say
    :object_namespace: true
  site/delicious:
    :object_namespace: true
    :commands:
    - bundles_all
    - posts_all
    - posts_recent
  what_methods:
  andand:
  sketches:
  gem:
    :dependencies: 
    - shell
  site/github:
    :dependencies:
    - boson
  site/wolfram:
  site/is_it_ruby19:
    :dependencies:
    - httparty
  rails/personal:
    :class_commands:
      reconnect: 'ActiveRecord::Base.connection.reconnect!'
      recognize_path: ActionController::Routing::Routes.recognize_path
      generate: ActionController::Routing::Routes.generate
  httparty:
    :force: true
    :class_commands:
      get: HTTParty.get
      post: HTTParty.post
      put: HTTParty.put
      delete: HTTParty.delete
  boson:
    :force: true
    :class_commands:
      any_const_get: Boson::Util.any_const_get
      detect: Boson::Util.detect
    :commands:
      detect:
        :description: Detect modules, gems and kernel methods loaded
      any_const_get:
        :description: Converts a string to a constant if it exists
  restclient:
    :force: true
    :class_commands:
      head: RestClient.head
      get: RestClient.get
      post: RestClient.post
      put: RestClient.put
      delete: RestClient.delete
  clipboard:
    :commands:
      paste: 
        :description: Paste to clipboard
      copy:
        :description: Copy to clipboard
    :class_commands:
      paste: Clipboard.read
      copy: Clipboard.write
  unroller:
    :object_methods: false
    :class_commands:
      trace: Unroller.trace
  local_gem:
    :module: LocalGem
    :gems:
    - local_gem
    :except:
    - setup_config
  tree:
    :dependencies:
    - core_gem
  hirb:
    :gems:
    - hirb
  core_gem:
    :gems:
    - core
:command_aliases:
  render: v
  libraries: lib
  commands: com
  nested_tree: ntree
  inheritance_tree: itree
  load_library: ll
  reload_library: rl
  history: hi
  edit_string: es
  toggle_echo: te
  delicious: del
  github: g
  highline: h
  toggle_hirb: th
  trace: tr
  songs_jump: sj
  current_variables: cv
  gem_recursive_uninstall: sgu
  checkout: co
  user_repos: ur
  analytics_day: ad
  unloaded_libraries: ul
  mls: ls
  mgrep: grep
  mwhich: which
  reload: re
  boson_library: bl
  boson_command: bc
  errorless_inheritance_tree: eit
  show_command: sc
  edit: e