# :auto_namespace: true
:bin_defaults:
- boson_method_missing
:console_defaults:
- boson_method_missing
- completion
- alias
- ruby_core
- method_lister
- core_gem
- boson
- irb_features
- local_gem
- duration
- hirb
- every
- rails/logger
- rails/personal
- rails/rails_core
- irb_core
:libraries:
  # file libraries- personal prefs
  alias:
    :object_methods: false
    :class_commands:
      create_aliases: Alias::Console.create_aliases
      save_aliases: Alias::Console.save_aliases
  gem_brain:
    :namespace: g
    :command_aliases:
      list: l
      tag: t
      add: a
      remove: rm
  site/is_it_ruby19:
    :namespace: r19
  boson:
    :force: true
    :class_commands:
      Boson::Util:
      - any_const_get
      - detect
    :commands:
      detect:
        :description: Detect modules, gems and kernel methods loaded
      any_const_get:
        :description: Converts a string to a constant if it exists
  # personal file libraries
  core_gem:
    :gems:
    - core
  clipboard:
    :commands:
      paste:
        :description: Paste to clipboard
      copy:
        :description: Copy to clipboard
    :class_commands:
      paste: Clipboard.read
      copy: Clipboard.write
  rails/personal:
    :class_commands:
      reconnect: 'ActiveRecord::Base.connection.reconnect!'
      recognize_path: ActionController::Routing::Routes.recognize_path
      generate: ActionController::Routing::Routes.generate
  site/delicious:
    :object_namespace: true
    :commands:
    - bundles_all
    - posts_all
    - posts_recent
  completion:
    :class_commands:
      spy: Bond.spy
  tree:
    :dependencies:
    - core_gem
  # gem libraries
  method_lister:
    :object_methods: false
    :command_aliases:
      mls: ls
      mgrep: grep
      mwhich: which
    :commands:
    - mls
    - mwhich
    - mgrep
  highline:
    :commands:
    - agree
    - ask
    - choose
    - say
    :object_namespace: true
  what_methods:
  andand:
  sketches:
  httparty:
    :force: true
    :class_commands:
      get: HTTParty.get
      post: HTTParty.post
      put: HTTParty.put
      delete: HTTParty.delete
  restclient:
    :force: true
    :class_commands:
      RestClient :
      - head
      - get
      - post
      - put
      - delete
  unroller:
    :object_methods: false
    :class_commands:
      trace: Unroller.trace
  local_gem:
    :class_commands:
      LocalGem:
      - local_gem
      - local_require
    :gems:
    - local_gem
:command_aliases:
  render: v
  libraries: lib
  commands: com
  nested_tree: ntree
  inheritance_tree: itree
  load_library: ll
  history: hi
  toggle_echo: te
  delicious: del
  highline: h
  toggle_hirb: th
  trace: tr
  songs_jump: sj
  current_variables: cv
  gem_recursive_uninstall: sgu
  checkout: co
  user_repos: ur
  analytics_day: ad
  unloaded_libraries: ul
  reload: re
  boson_library: bl
  boson_command: bc
  errorless_inheritance_tree: eit
  show_command: sc
  edit: e
  instance_var_table: ivt