# :auto_namespace: true
:defaults:
- public/plugins/meth_missing
- public/plugins/options
:console_defaults:
- personal/completion
- personal/alias
- public/ruby_core
- method_lister
# - personal/core_gem
- public/boson
- public/irb_features
- public/duration
- personal/hirb
- every
- public/rails/logger
- personal/rails
- public/rails/rails_core
- public/irb_core
:libraries:
  # file libraries- personal prefs
  public/ruby_ref:
    :commands:
      loaded_paths:
        :default_option: query
  public/ruby_core:
    # thanks rake
    :force: true
  public/site/github:
    :commands:
      user_repos:
        :render_options:
          :reverse_sort: true
          :sort:
            :default: :watchers
  public/file:
    :class_commands:
      file_read : File.read
    :commands:
      file_read:
        :alias: fr
        :description: File to string
  public/boson:
    :class_commands:
      Boson::Util:
      - any_const_get
      - detect
      boson_library: Boson.library
      boson_command: Boson::Command.find
    :commands:
      boson_command:
        :description: Get command object by name or alias
      boson_library:
        :description: Get library object by name
      detect:
        :description: Detect modules, gems and kernel methods loaded
      any_const_get:
        :description: Converts a string to a constant if it exists
  # personal file libraries
  personal/alias:
    :object_methods: false
    :class_commands:
      create_aliases: Alias::Console.create_aliases
      save_aliases: Alias::Console.save_aliases
  exp/gem_brain:
    :namespace: g
    :command_aliases:
      list: l
      tag: t
      add: a
      remove: rm
  personal/core_gem:
    :gems:
    - core
  clipboard:
    :commands:
      paste:
        :description: Paste to clipboard
      copy:
        :description: Copy to clipboard
    :class_commands:
      paste: Clipboard.read
      copy: Clipboard.write
  personal/rails:
    :class_commands:
      reconnect: 'ActiveRecord::Base.connection.reconnect!'
      recognize_path: ActionController::Routing::Routes.recognize_path
      generate: ActionController::Routing::Routes.generate
  exp/delicious:
    :object_namespace: true
    :commands:
    - bundles_all
    - posts_all
    - posts_recent
  personal/completion:
    :class_commands:
      spy: Bond.spy
  # gem libraries
  method_lister:
    :object_methods: false
    :command_aliases:
      mls: ls
      mgrep: grep
      mwhich: which
    :commands:
    - mls
    - mwhich
    - mgrep
  exp/highline:
    :commands:
    - agree
    - ask
    - choose
    - say
    :object_namespace: true
  what_methods:
  andand:
  sketches:
  httparty:
    :force: true
    :class_commands:
      get: HTTParty.get
      post: HTTParty.post
      put: HTTParty.put
      delete: HTTParty.delete
  restclient:
    :force: true
    :class_commands:
      RestClient :
      - head
      - get
      - post
      - put
      - delete
  unroller:
    :object_methods: false
    :class_commands:
      trace: Unroller.trace
  local_gem:
    :class_commands:
      LocalGem:
      - local_gem
      - local_require
    :gems:
    - local_gem
:command_aliases:
  render: v
  libraries: lib
  commands: com
  nested_tree: ntree
  inheritance_tree: itree
  load_library: ll
  history: hi
  toggle_echo: te
  delicious: del
  highline: h
  toggle_hirb: th
  trace: tr
  songs_jump: sj
  current_variables: cv
  gem_recursive_uninstall: sgu
  checkout: co
  user_repos: ur
  analytics_day: ad
  unloaded_libraries: ul
  reload: re
  boson_library: bl
  boson_command: bc
  errorless_inheritance_tree: eit
  show_command: sc
  edit: e
  instance_var: inv
:global_options:
  :browser:
    :type: :boolean
    :desc: Open in browser
    :pipe: true
  :copy:
    :type: :boolean
    :desc: Copy to clipboard
    :pipe: true
  :pastie:
    :alias: P
    :type: :boolean
    :desc: Paste to pastie
    :pipe: true
  :slice:
    :alias:
    - S
    - z
    :type: :string
    :desc: Slice a list
    :pipe: multislice
    :filter: true
:render_options:
  :all_fields:
    :type: :boolean
    :desc: Show all fields
  :number:
    :type: :boolean
    :desc: Number rows
  :method:
    :type: :string
    :desc: Render method