:defaults:
- console
- completion
- alias
- method_lister
- core_gem
- tree
- misc
- silencer
- shell
- boson
:libraries:
  method_lister:
    :object_methods: false
    :commands:
    - mls
    - mwhich
    - mgrep
  alias:
    :object_methods: false
  irb/extend_command_bundle:
    :commands:
    - irb_pop_workspace
    - irb_source
    - irb_help
    - irb_context
    - irb_load
    - irb_jobs
    - irb_workspaces
    - irb
    - public
    - irb_exit
    - irb_fg
    - irb_require
    - irb_kill
    - include
    - install_alias_method
    - irb_current_working_workspace
    - irb_change_workspace
    - private
    - irb_push_workspace
  irb_features:
    :init_methods:
    - irb_options
    - railsrc
    - history
    - irb_prompts
  completion:
    :no_module_eval: true
    :init_methods:
    - load_bond
  history:
    :dependencies:
      - console
  what_methods:
  andand:
  sketches:
  gem:
    :dependencies: 
    - shell
  site/github:
    :namespace: github
  site/wolfram:
  site/is_it_ruby19:
    :dependencies:
    - httparty
  rails/model_find_shortcuts:
    :init_methods:
    - define_model_shortcuts
  httparty:
    :force: true
    :class_commands:
      get: HTTParty.get
      post: HTTParty.post
      put: HTTParty.put
      delete: HTTParty.delete
  boson:
    :class_commands:
      any_const_get: Boson::Util.any_const_get
      detect: Boson::Util.detect
  restclient:
    :force: true
    :class_commands:
      head: RestClient.head
      get: RestClient.get
      post: RestClient.post
      put: RestClient.put
      delete: RestClient.delete
  clipboard:
    :class_commands:
      paste: Clipboard.read
      copy: Clipboard.write
  unroller:
    :detect_object_methods: false
    :class_commands:
      trace: Unroller.trace
  local_gem:
    :module: LocalGem
    :gems:
    - local_gem
    :except:
    - setup_config
  tree:
    :dependencies:
    - core_gem
  hirb:
    :init_methods:
    - setup_hirb
    :module: Boson::Commands::Hirb
    :gems:
    - hirb
  core_gem:
    :gems:
    - core
:commands:
  irb_jobs:
    :alias: jobs
    :description: list workspaces/subsessions
  irb_fg:
    :alias: fg
    :description: switch to a workspace/subsession
  irb_kill:
    :alias: kill
    :description: kills a given workspace/subsession
  irb_exit:
    :alias: exit
    :description: kills the current workspace/subsession
  irb_context:
    :alias: conf
    :description: displays configuration for current workspace/subsession
  irb:
    :description: starts a new workspace/subsession
  install_alias_method:
    :description: aliases given method, allows lazy loading of dependent file
  irb_change_workspace:
    :alias: cws
    :description: changes current workspace to given object
  irb_push_workspace:
    :alias: pushws
    :description: creates a workspace for given object and pushes it into the current context
  irb_pop_workspace:
    :alias: popws
    :description: pops current workspace and changes to next workspace in context
  irb_current_working_workspace:
    :alias: cwws
    :description: prints current workspace
  irb_workspaces:
    :alias: workspaces
    :description: array of workspaces for current context
  irb_help:
    :alias: help
    :description: ri based help
  irb_source:
    :alias: source
    :description: evals full path file line by line
  irb_load:
    :description: evals file like load line by line
  irb_require:
    :description: evals file like require line by line
  include:
    :description: works same as Module#include
  private:
    :description: works same as Module#private
  public:
    :description: works same as Module#public
:command_aliases:
  render: v
  libraries: lib
  commands: com
  nested_tree: ntree
  inheritance_tree: itree
  load_library: ll
  reload_library: rl
  print_history: ph
  edit_and_eval: ee
  edit_history: eh
  clipboard_paste: pbp
  clipboard_copy: pbc
  irb_verbosity_toggle: iv
  delicious: del
  toggle_hirb: th
  trace: tr
  songs_jump: sj
  current_variables: cv
  gem_recursive_uninstall: sgu
  checkout: co
  analytics_day: ad
  github: g
  unloaded_libraries: ul
  mls: ls
  mgrep: grep
  mwhich: which
  reload: re