:defaults:
- console
- completion
- alias
- method_lister
- core_gem
- tree
- misc
- silencer
- shell
- boson
- irb_features
- history
- local_gem
- wirble
- clipboard
- duration
- hirb
- every
- rails/main
:libraries:
  method_lister:
    :object_methods: false
    :commands:
    - mls
    - mwhich
    - mgrep
  alias:
    :object_methods: false
    :no_alias_creation: true
  irb_features:
    :init_methods:
    - irb_options
    - railsrc
    - history
    - irb_prompts
  completion:
    :init_methods:
    - load_bond
  history:
    :dependencies:
      - console
  highline:
    :commands:
    - agree
    - ask
    - choose
    - say
    :namespace: true
  what_methods:
  andand:
  sketches:
  gem:
    :dependencies: 
    - shell
  site/github:
    :namespace: github
    :object_methods: false
    :dependencies:
    - boson
  site/wolfram:
  site/is_it_ruby19:
    :dependencies:
    - httparty
  rails/main:
    :class_commands:
      reconnect: 'ActiveRecord::Base.connection.reconnect!'
      recognize_path: ActionController::Routing::Routes.recognize_path
      generate: ActionController::Routing::Routes.generate
  rails/model_find_shortcuts:
    :init_methods:
    - define_model_shortcuts
  httparty:
    :force: true
    :class_commands:
      get: HTTParty.get
      post: HTTParty.post
      put: HTTParty.put
      delete: HTTParty.delete
  boson:
    :force: true
    :class_commands:
      any_const_get: Boson::Util.any_const_get
      detect: Boson::Util.detect
  restclient:
    :force: true
    :class_commands:
      head: RestClient.head
      get: RestClient.get
      post: RestClient.post
      put: RestClient.put
      delete: RestClient.delete
  clipboard:
    :class_commands:
      paste: Clipboard.read
      copy: Clipboard.write
  unroller:
    :object_methods: false
    :class_commands:
      trace: Unroller.trace
  local_gem:
    :module: LocalGem
    :gems:
    - local_gem
    :except:
    - setup_config
  tree:
    :dependencies:
    - core_gem
  hirb:
    :init_methods:
    - setup_hirb
    :gems:
    - hirb
  core_gem:
    :gems:
    - core
:command_aliases:
  render: v
  libraries: lib
  commands: com
  nested_tree: ntree
  inheritance_tree: itree
  load_library: ll
  reload_library: rl
  print_history: ph
  edit_and_eval: ee
  edit_history: eh
  clipboard_paste: pbp
  clipboard_copy: pbc
  irb_verbosity_toggle: iv
  delicious: del
  github: g
  highline: h
  toggle_hirb: th
  trace: tr
  songs_jump: sj
  current_variables: cv
  gem_recursive_uninstall: sgu
  checkout: co
  analytics_day: ad
  unloaded_libraries: ul
  mls: ls
  mgrep: grep
  mwhich: which
  reload: re